config/routes.rb
Webblog::Application.routes.draw do
  resources :users

  get "static_pages/contact"

  get "static_pages/school"

  get "static_pages/links"

  get "static_pages/about"

  get "pages/index"

  get "users/index"
  resources :posts do
    resources :comments
  end 

  match '/projects' => 'static_pages#projects'
  match '/links' => 'static_pages#links'
  match '/internships' => 'static_pages#internships'
  match '/school' => 'static_pages#school'
  match '/resume' => 'users#index'

  root :to => "home#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :commenter
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :name, :title, :tags_attributes

  validates :name, :presence => true
  validates :title, :presence => true,
                    :length => { :minimum => 5 }
  has_many :comments, :dependent => :destroy
  has_many :tags

  accepts_nested_attributes_for :tags, :allow_destroy => :true,
    :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with :name => "ninjapanda57", :password => "9z9y1QAZ2wsx", :except => [:index, :show]
	def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end
 
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def projets
  end

  def resume
  end

  def internships
  end

  def school
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json

  http_basic_authenticate_with :name => "ninjapanda57", :password => "9z9y1QAZ2wsx", :except => [:index, :show]
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, :notice => 'Post was successfully created.' }
        format.json { render :json => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, :notice => 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end

  def school
  end

  def links
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        UserMailer.registration_confirmation(@user).deliver
        format.html { redirect_to @user, :notice => 'Email was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def join_tags(post)
    post.tags.map { |t| t.name }.join(", ")
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>
	<b>Commenter:</b>
  <%= comment.commenter %>
</p>
 
<p>
  <b>Comment:</b>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               :confirm => 'Are you sure?',
               :method => :delete %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<%end%>

app/views/home/index.html.erb
<html>        
        <div class="span9 pagination-centered">  
          <div class="leaderboard">  
            <h1>Learn. Develop. Inspire.</h1>  
            <p>My name is Tiffani Dutton and I am currently a Senior in Computer Science at Missouri S&T. </p>  
          </div> 
          <div class="span4 offset2">
          <%= image_tag("me.png", :alt => "me!") %>
        </div>
          <div class="row-fluid">  
            <div class="span4">  
              <h2>Learn</h2>  
              <p>I'm getting my B.S. in Computer Science from Missouri S&T (UMR), I will be graduating May of 2014 and am actively seaking fulltime employment</p>  
             <!-- <p><a class="btn btn-success btn-large" href="#">Learn Now!</a></p> --> 
            </div><!--/span-->  
            <div class="span4">  
              <h2>Develop</h2>  
              <p>I am currently working on an App for Android Phones. It will allow people to keep track of video games that they personally own as well as price check video games they find at stores.</p>  
             <!--- <p><a class="btn btn-success btn-large" href="#">See What I've Developed!</a></p>  -->
            </div><!--/span-->  
            <div class="span4">  
              <h2>Inspire</h2>  
              <p>Through the help of Twitter Bootstrap, and other Rails sites this whole site was made possible.</p>  
              <!--<p><a class="btn btn-success btn-large" href="#"></a></p>  -->
            </div><!--/span-->  
          </div><!--/row-->  
          <hr> 

          </body> 
    
</html>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tiffani's Website</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">  
    <meta name="description" content="Tiffani Dutton's web site">  
    <meta name="author" content="">
  <link href="../../assets/stylesheets/bootstrap.css" rel="stylesheet">  
  <link href="../../assets/stylesheets/example-fluid-layout.css" rel="stylesheet">
   <div class="navbar navbar-fixed-top"> 
    <div class="navbar-inner">  
      <div class="container-fluid">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">  
            <span class="icon-bar"></span>  
            <span class="icon-bar"></span>  
            <span class="icon-bar"></span>  
        </a> 
        <div class="container">  
          <div class="row">  
            <div class="span6">  
              <ul class="nav pull-left">   
              <li><%=link_to "Home", root_path%></li>  
              <li><%= link_to "About", static_pages_about_path %></li>
              <li><%= link_to "Resume", resume_path %></li>
              <li><%= link_to "School", static_pages_school_path %></li>
              <!---<li><%= link_to "Helpful Links", static_pages_links_path%></li>---->
              <li><%= link_to "My Blog",posts_path%></li>
              </ul>  
              <ul class="nav pull-left">
                <li><a href="https://www.facebook.com/tiffani.dutton?ref=tn_tnmn" target="_blank">
                  <%= image_tag("facebook.png", :alt => "facebook") %></a></li>  
              <li><a href="https://twitter.com/ninjapanda57" target="_blank">
              <%= image_tag("twitter.png", :alt => "twitter") %>
              </a></li>

              <li><a href="https://plus.google.com/u/1/103506770754868070544" target="_blank">
              <%= image_tag("gplus.png", :alt => "gplus")%>
              </a></li>

              <li><a href="http://www.linkedin.com/profile/view?id=111580522&trk=hb_tab_pro_top" target="_blank">
              <%= image_tag("linkedin.png", :alt => "linkedin") %>
              </a></li> 
            </ul>
            </div>  
          </div>  
        </div>
        </div>
      </div>
    </div>

  </div>
</head>
<body>

<%= yield %>
</body>

<footer> 
              
  </footer> 
<script src="../../assets/js/jquery.js"></script>  
<script src="../../assets/js/bootstrap-transition.js"></script>  
<script src="../../assets/js/bootstrap-alert.js"></script>  
<script src="../../assets/js/bootstrap-modal.js"></script>  
<script src="../../assets/js/bootstrap-dropdown.js"></script>  
<script src="../../assets/js/bootstrap-scrollspy.js"></script>  
<script src="../../assets/js/bootstrap-tab.js"></script>  
<script src="../../assets/js/bootstrap-tooltip.js"></script>  
<script src="../../assets/js/bootstrap-popover.js"></script>  
<script src="../../assets/js/bootstrap-button.js"></script>  
<script src="../../assets/js/bootstrap-collapse.js"></script>  
<script src="../../assets/js/bootstrap-carousel.js"></script>  
<script src="../../assets/js/bootstrap-typeahead.js"></script>  
</body>
</html>

app/views/pages/helpers.html.erb
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html"; charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <!--
    <link rel="stylesheet" type="text/css" href="/static/global.css">
    -->
    <link rel="stylesheet" type="text/css" href="/static/smoothness/jquery-ui-1.10.0.custom.min.css">
    <link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css">
    <!--[if ie]><meta content='IE=8' http-equiv='X-UA-Compatible'/><![endif]-->
    <link href="/static/bootstrap/css/bootstrap-responsive.css" rel="stylesheet" type="text/css">   
    <!--link href="/static/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"-->      
    <link href="/static/bootstrap/css/paralax.css" rel="stylesheet" type="text/css">
    <link href="/static/bootstrap/css/main.css" rel="stylesheet" type="text/css">
    <!--[if lt IE 9]>
            <link href="css/ie.css" rel="stylesheet"/>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>      
            <script src="js/css3-mediaqueries.js"></script>
    <![endif]-->




        <script src="/static/bootstrap/js/modernizr.custom.js"></script>    
        <script src="/static/js/jquery-1.9.0.js"></script>
        <script src="/static/js/jquery-ui-1.10.0.custom.min.js"></script>
        <script src="/static/bootstrap/js/jquery.scrolltotop.js"></script>
        <script src="/static/bootstrap/js/jquery-1.7.2.min.js"></script>
        <script src="/static/highcharts-3/js/highcharts.js"></script>
        <script src="/static/bootstrap/js/bootstrap.min.js"></script>
        <script src="/static/bootstrap/js/superfish.js"></script>

    <title>CoAssets Platform (BETA)</title>
</head>

<body>

    <!--div class="container-fluid"-->
        <div class="row-fluid">
            <div class="span12" id="topmenu">
            {% block topmenu %}{% endblock %}
            </div>
        </div>

        <div class="row-fluid" style="background-color:#ffad37">
            <div class="span12" id="submenu" style="padding-top:2px; padding bottom:2px">
            <ul class="nav nav-pills">          
                {% block submenu %}{% endblock %}
                <li class="pull-right"><a class="btn" href="/account/logout" style="font-size: 16px; font-family: 'PT Sans', sans-serif; text-align: center;">Logout</a>
                <li class="pull-right"><a href="/account/">Account</a></li>
            </ul>
            </div>  
        </div>
    <!--/div-->

    <!--div class="container-fluid"-->
        <div class="row-fluid">
            <div class="span12" id="main">
                {% block main_body %}{% endblock %}
            </div>
        </div> 
    <!--/div-->
    </br>
    <div class="container-fluid" id="copyright">    
        <div class="row-fluid">
            <div class="span4">
                <p>Legalise</p>
                <p>Contact Us</p>
            </div>
            <div class="span4">
                <p>Partners</p>
                <p>FAQ</p>
                <p>Definitions</p>
            </div>
            <div class="span4">
                <p><a  href="/util/">Admin</a></p>
            </div>
        </div>
        <div class="row-fluid" id="copyright">
            <div class="span12" id="footer">
                <p>Copyright of CoAssets.com &copy; 2013</p>
            </div>
        </div>      
    </div>


<script>
//script conflicts with some other jQuery scripts, so need to handle this script
jQuery.noConflict();
$(document).ready(function($){  
    $('.nav li').each(function() {
        var currentPath = window.location.pathname;
        var thisPath = $(this).children().attr('href');
        //alert("sub menu currentPath= "+currentPath+" thisPath= "+thisPath);
        $(this).removeClass('active');
        if (thisPath == currentPath && !$(this).hasClass('active')) {
            $(this).addClass('active');
        };
    });

    $('#menu li').each(function() {
        var currentPath = window.location.pathname;
        var thisPath = $(this).children().attr('href');
        var len = thisPath.length;
        //alert("top menu currentPath= "+currentPath+" thisPath= "+thisPath);
        $(this).removeClass('active');
        if (thisPath != '/' && thisPath == currentPath.substring(0,len) 
                                                    && !$(this).hasClass('active')) {
            $(this).addClass('active');
        } else if (thisPath=='/' && currentPath == '/')
        {
            $(this).addClass('active');
        };
    });
});
</script>


</body>
</html>



{% extends "base.html" %}

{% block topbar %}

{% endblock %}

{% block topmenu %}
    <section class="navbar">
        <div class="navbar-inner main-menu">
            <div class="row-fluid">
                <div class="span2">
                    <a href="www.ascendantassets.com" class="logo pull-left"><img src="/public_media/index_01 edited4.png" alt=""></a>      
                </div>
                <div class="span10">
                    <nav id="menu" class="pull-right" >
                        <ul>
                            <li class="active"><a href="/">Home<br/><span>CoAssets</span></a></li>
                            <li><a href="/cms/view/">News</a></li>      
                            <li><a href="/portfolio/">Portfolio</a></li>                    
                            <li><a href="/property/">Opportunities</a></li>
                            <li><a href="/ipo/">New Opportunities</a></li>
                            <li><a href="/transaction/">Transaction</a></li>
                            <li><a href="/analytics/npv/">Research</a></li> 
                            <!--li><a href="/account/">Account</a></li-->
                            <!--li><a href="/util/">Admin</a></li-->
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </section>

    {%comment%}
    <div class="label label-warning offset2">
        <p>CoAssets Beta</p>
    </div>
    {%endcomment%}


{% endblock %}

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="theiahtweith" style="float:left;">
<center><h1>Listing posts</h1></center>
	<hr>
	<br>
	<br>

<table>
  

<% @posts.each do |post| %>
  <tr><p><u><h2><%= post.title %></h2></u></p></tr>
  <tr><p><%= post.content %> </p></tr>
  <tr>by:<i> <%= post.name %></i>&nbsp;&nbsp;&nbsp;<%= link_to 'Edit', edit_post_path(post) %></tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>
</center>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
 
<p>
  <b>Name:</b>
  <%= @post.name %>
</p>
 
<p>
  <b>Title:</b>
  <%= @post.title %>
</p>
 
<p>
  <b>Content:</b>
  <%= @post.content %>
</p>
 

 
<h2>Comments</h2>
<%= render @post.comments %>
 
<h2>Add a comment:</h2>
<%= render "comments/form" %>
 
 
<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %> |

app/views/static_pages/about.html.erb
<div class="span9">  
          <div class="leaderboard">  
            <center><h1>About</h1> </center>    
          <div class="row-fluid pagination-centered">  
            <div class="span6">
              <h2>Hobbies</h2>  
              <p><dt>Playing League of Legends</dt>
				<dd>-Summoner name: Allestar</dd>
				<dt>Music</dt>
				<dd>-Violin player for 17 years</dd>
				<dd>-Ukulele player for 2 years.</dd></p>
            </div><!--/span-->  
            <div class="span6">  
              <h2>Organizations</h2>  
              <p>
              	<dt>National Residence Hall Honorary (NRHH)</dt>
				<dd>-General Member Winter 2012 - Current</dd>
				<dt>Association of Computer Machinery</dt>
				<dd>- General Member since 2011, Secretary 2013-2014</dd>
              </p>
            </div><!--/span--> 
            </div><!--/row-->
            <div class="row-fluid pagination-centered"> 
            <div class="span6">  
              <h2>School</h2>  
              <p> 
              	<dt>Missouri University of Science and Technology (Formerly UMR)</dt>
				<dd>-B.S. Computer Science <i>Graduation Date:</i>   May 2014</dd>
              </p>  
            </div><!--/span--> 
           <div class="span6">
           	<h2>Residential Life</h2>
           	<p>
           	<dt>Resident Assistant</dt>
				<dd>-2011-2012 in Thomas Jefferson hall</dd>
				<dt>Senior Resident Assitant</dt>
				<dd>-2012-2013 in Residential College</dd>
				<dt>Head Resident</dt>
				<dd>-2013-2014 Quadulangular Complex</dd>
			</p> 
          </div><!--/row-->

app/views/static_pages/contact.html.erb
<h1> Contact</h1>

if you have any questions about the web site feel free to email me at info.tiffani.dutton@gmail.com

app/views/static_pages/links.html.erb
<h1>Links</h1>


<div class="row-fluid">  
            <div class="span4">
              <h2>Google</h2>  
              <p>Now, I know this might seem obvious, but to many people it is not, a simple google search can help you through anything you need and can help you find helpful links and pages.</p>  
             <p><a class="btn btn-success btn-large" href="http://www.google.com">Google</a></p> 
            </div><!--/span-->  
            <div class="span4">  
              <h2>Stack Overflow</h2>  
              <p>Have a really obscure problem? Think it may have never been solved before. You may be wrong, stack overflow is a forum that allows people to post code and have the world that is Stack Overflow help you fix your problems!</p>  
              <p><a class="btn btn-success btn-large" href="http://stackoverflow.com/" target="_blank">Stack Overflow</a></p>
            </div><!--/span-->  
            <div class="span4">  
              <h2>Twitter Bootstrap</h2>  
              <p>Want a slick looking website but don't know how to code the 2000 line css page? Want help in making different parts of your web page slick, well twitter bootstrap is the place for you! It has so many demos and guides and help to get your site started!</p>  
              <p><a class="btn btn-success btn-large" href="http://twitter.github.io/bootstrap/">Twitter Bootstrap</a></p>
            </div><!--/span-->  
          </div><!--/row-->  

          <br>
          <hr>
          <br>

          <div class="row-fluid">  
            <div class="span4">
              <h2>GoRails</h2>  
              <p>Go Rails is a project from one of my reall good friends. He's probably one of those people that you think of when you need help especially when it comes to ruby on rails. This site gives guides and suggestions on what you should be doing or how to add specific gems to your application.</p>  
             <p><a class="btn btn-success btn-large" href="http://www.gorails.com">Go Rails</a></p> 
            </div><!--/span-->  
            <div class="span4">  
              <h2>Rails Casts</h2>  
              <p>Are you more of a visual learner then an reader? Then Rails Casts will be the best way to get your information, there are videos as well as written guides to explain what's going on when you add different models, as well as interacting with different gems. </p>  
             <p><a class="btn btn-success btn-large" href="http://www.railscasts.com">Rails Casts</a></p>
            </div><!--/span-->  
            <div class="span4">  
              <h2>Udacity</h2>  
              <p>Udacity is a free easy friendly website that can give you classes. There are many different classes that you can take in the range from intro to computer programming to artificial intelligence.</p>  
              <p><a class="btn btn-success btn-large" href="https://www.udacity.com/">Udacity</a></p>
            </div><!--/span-->  
          </div><!--/row-->  

          <br>
          <hr>
          <br>

          <div class="row-fluid">  
            <div class="span4">
              <h2>W3Schools</h2>  
              <p>If you really need physical code of whats going on, but when you look at guides there is too much other stuff clouding the information then W3 school is exactly what you are looking for. If you need a simple example W3 school will give you the bare bones minimum of what you need to do to accomplish your task.</p>  
             <p><a class="btn btn-success btn-large" href="http://www.w3schools.com">w3schools</a></p> 
            </div><!--/span-->  
            <div class="span4">  
              <h2>Apidock</h2>  
              <p>ApiDock is a way to get better at documentation within a site that you are working on. It also gives you specific help with Rails.</p>  
             <p><a class="btn btn-success btn-large" href="http://www.apidock.com">ApiDock</a></p>
            </div><!--/span-->  
            <div class="span4">  
              <h2>Project Euler</h2>  
              <p>Need to learn a new programming language? Then this place will be an easy way to learn a new programming language. Project Euler is a database of math questions that you can solve using different languages.</p>  
              <p><a class="btn btn-success btn-large" href="http://projecteuler.net">Project Euler</a></p>
            </div><!--/span-->  
          </div><!--/row-->  

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
  <div class="field">
    <%= tag_form.label :name, 'Tag:' %>
    <%= tag_form.text_field :name %>
  </div>
  <% unless tag_form.object.nil? || tag_form.object.new_record? %>
    <div class="field">
      <%= tag_form.label :_destroy, 'Remove:' %>
      <%= tag_form.check_box :_destroy %>
    </div>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit "Request Resume" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="pagination-centered"><h1>Request a resume!</h1>

Please click below to request a resume! 

<%= link_to 'Resume form', new_user_path %></div>

<p>If you have any questions please feel free to email me at <a href="mailto:email@echoecho.com?subject=Question for Tiffani Dutton">
info.tiffani.dutton@gmail.com</a> 

app/views/users/new.html.erb
<h1>Request a Resume!</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>
<p style="color:green"> Thank you for requesting my resume! You should recieve an email shortly!</p>
</h1>